# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PianExporter
                                 A QGIS plugin
 Plugin exportuje vrstvu do formátu pro pian
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-26
        copyright            : (C) 2024 by Marek Lečbych
        email                : lecbych@uapp.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PianExporter class from file PianExporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pian_exporter import PianExporter
    return PianExporter(iface)
